### ISSUE TITLE
What are the versions of tensorflow and keras, respectively?

### ISSUE THREAD

**Issue by xiaozialei** [oarriaga/single_shot_multibox_detector#1]
Thanks for you excellent implementaion.
What are the versions of tensorflow and keras, respectively?

**Comment by oarriaga** [comment]
Hello @xiaozialei,
Thank you for the interest in the code. Unfortunately it is not complete yet; therefore, I haven't created a README or REQUIREMENTS. Haven said that the current keras/tensroflow versions I am using are 2.05/1.10 respectively.

**Comment by mrqorib** [comment]
@oarriaga Is it still not complete now?

**Comment by oarriaga** [comment]
Almost ;-)

**Comment by mrqorib** [comment]
@oarriaga could you please let me know when it's complete? :)
